Only schedule refresh task in onEnable, versus Menu.init: If no menu was ever opened, and the plugin was disabled, an exception would be thrown because the class would try to schedule a task in onDisable Also, wrap onDisable code in try/catch for NoClassDefFoundError in case any of the classes referenced were not loaded